# Generated by Django 5.0 on 2023-12-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='categories',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in progress', 'in progress'), ('completed', 'completed')], default='pending', max_length=11),
        ),
    ]
